version: "3.8"

services:
  postgres_db:
    container_name: db
    image: postgres:15.0
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PORT: ${POSTGRES_PORT}
    ports:
      - $POSTGRES_PORT:5432
    volumes:
      - ./.docker/db/data/:/var/lib/postgresql/data/:rw
      - ./schema.sql:/docker-entrypoint-initdb.d/schema.sql:ro

  # go:
  #   container_name: app
  #   build: 
  #     context: ./
  #     dockerfile: ./.docker/go/Dockerfile


      